version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build

  artifacts:
    files:
      - '**/*'
    base-directory: 'build'

  deploy:
    commands:
      - aws s3 cp build/ s3://my-bucket/
