version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.0
    commands:
      - nvm install 20.15.0
      - nvm use 20.15.0
      - echo Installing dependencies...
        - npm install --frozen-lockfile

  build:
    commands:
      - echo Build started on `date`
        - npm build

artifacts:
  files:
    - '**/*'

deploy:
  commands:
    - aws s3 cp build/ s3://my-bucket/
