version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'

# This section is optional
# It will be used to deploy the build artifact to an S3 bucket
deploy:
  commands:
    - aws s3 cp build/ s3://my-bucket/
