/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7c16800c-4aba-4dbe-842b-c239b6d4090b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_C0j2dshTh",
    "aws_user_pools_web_client_id": "4nanf78sthg79fgvbpfqc8ovo0",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "thbigbraintechbucket31eba-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
